from labyrinth import Labyrinth

labyrinth = Labyrinth()

# labyrinth.seekers[0].move(labyrinth.grid, [1, 0])
print("sh",labyrinth.shortest_distance_to_runner())
print(labyrinth.fitness(15))
print(labyrinth.seekers[0].position)
print("rea",labyrinth.tiles_reachable_by_runner())
labyrinth.seekers[0].move(labyrinth.grid, [-1, 0])
labyrinth.seekers[0].move(labyrinth.grid, [0, 1])
labyrinth.seekers[0].move(labyrinth.grid, [0, 1])
labyrinth.seekers[0].move(labyrinth.grid, [1, 0])
labyrinth.seekers[0].move(labyrinth.grid, [0, 1])
labyrinth.seekers[0].move(labyrinth.grid, [0, 1])
labyrinth.seekers[0].move(labyrinth.grid, [0, 1])
labyrinth.seekers[0].move(labyrinth.grid, [-1, 0])
labyrinth.seekers[0].move(labyrinth.grid, [0, 1])
labyrinth.seekers[0].move(labyrinth.grid, [0, 1])
labyrinth.seekers[0].move(labyrinth.grid, [1, 0])
labyrinth.seekers[0].move(labyrinth.grid, [1, 0])
print(labyrinth.seekers[0].position)
print(labyrinth.fitness(15))